# Generated by Django 2.2.16 on 2021-02-24 12:18

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_feedbackurlconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagingLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("USER", "User"), ("GROUP", "Group")],
                        default="USER",
                        max_length=5,
                    ),
                ),
                ("send_action_uuid", models.UUIDField(default=uuid.uuid4)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
