# Generated by Django 2.2.17 on 2021-04-06 20:14

from django.db import migrations, models
from allauth.socialaccount.models import SocialApp
from django.contrib.sites.models import Site
from eahub.config.settings import DjangoEnv


def load_seed_data(apps, schema_editor):
    env = environ.Env().get_value("DJANGO_ENV", DjangoEnv, default=DjangoEnv.LOCAL)

    if env == DjangoEnv.LOCAL or env == DjangoEnv.E2E:
        socialApp = SocialApp(provider="google")
        socialApp.save()
        socialApp.sites.set([Sites.objects.first()])


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_add_name_fields_for_sso"),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
