# Generated by Django 2.1.4 on 2019-01-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190105_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gdpr_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
