# Generated by Django 2.1.5 on 2019-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190129_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='volunteer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
