# Generated by Django 2.1.5 on 2019-01-30 03:41

from django.db import migrations
import django_upload_path.upload_path
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190129_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4),
        ),
    ]
