# Generated by Django 2.1.5 on 2019-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='org_affiliations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='profile',
            name='available_as_speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='available_to_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='cause_areas_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='open_to_job_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='topics_i_speak_about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cause_areas',
            field=models.CharField(blank=True, choices=[('GLOBAL_POVERTY', 'Global Poverty'), ('ANIMAL_WELFARE_AND_RIGHTS', 'Animal Welfare/Rights'), ('LONG_TERM_FUTURE', 'Long-term Future'), ('CAUSE_PRIORITISATION', 'Cause Prioritisation'), ('META', 'Meta'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'Management'), ('OPERATIONS', 'Operations'), ('RESEARCH', 'Research'), ('GOVERNMENT_AND_POLICY', 'Government and policy'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('SOFTWARE_ENGINEERING', 'Software engineering'), ('AI_TECHNICAL_EXPERTISE', 'AI technical expertise'), ('MATH_QUANT_STATS_EXPERTISE', 'Math, quant, stats expertise'), ('ECONOMICS, QUANTITATIVE SOCIAL SCIENCE', 'Economics, quantitative social science'), ('MOVEMENT_BUILDING', 'Movement building'), ('COMMUNICATIONS', 'Communications'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
