# Generated by Django 2.1.5 on 2019-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190131_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cause_areas',
            field=models.CharField(blank=True, choices=[('GLOBAL_POVERTY', 'Global Poverty'), ('ANIMAL_WELFARE_AND_RIGHTS', 'Animal Welfare/Rights'), ('LONG_TERM_FUTURE', 'Long-term Future'), ('CAUSE_PRIORITISATION', 'Cause Prioritisation'), ('META', 'Meta'), ('OTHER', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'Management'), ('OPERATIONS', 'Operations'), ('RESEARCH', 'Research'), ('GOVERNMENT_AND_POLICY', 'Government and policy'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('SOFTWARE_ENGINEERING', 'Software engineering'), ('AI_TECHNICAL_EXPERTISE', 'AI technical expertise'), ('MATH_QUANT_STATS_EXPERTISE', 'Math, quant, stats expertise'), ('ECONOMICS, QUANTITATIVE SOCIAL SCIENCE', 'Economics, quantitative social science'), ('MOVEMENT_BUILDING', 'Movement building'), ('COMMUNICATIONS', 'Communications'), ('OTHER', 'Other')], max_length=38, null=True),
        ),
    ]
