# Generated by Django 2.1.5 on 2019-01-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190131_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='summary',
        ),
    ]
