# Generated by Django 2.1.5 on 2019-01-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190131_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available_as_speaker',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='available_to_volunteer',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='open_to_job_offers',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
