# Generated by Django 2.1.5 on 2019-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20190131_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='giving_pledge',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('YES_GIVING_WHAT_WE_CAN', 'Yes, with Giving What We Can'), ('YES_THE_LIFE_YOU_CAN_CHANGE', 'Yes, with The Life You Can Save'), ('YES_ONE_FOR_THE_WORLD', 'Yes, with One for the World'), ('YES_OTHER', 'Yes, Other')], max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='giving_pledge_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
