# Generated by Django 2.1.5 on 2019-02-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20190206_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='giving_pledge',
            field=models.CharField(blank=True, choices=[('', 'No'), ('GIVING_WHAT_WE_CAN', 'Giving What We Can'), ('THE_LIFE_YOU_CAN_CHANGE', 'The Life You Can Save'), ('ONE_FOR_THE_WORLD', 'One for the World'), ('OTHER', 'Other')], max_length=23, null=True),
        ),
    ]
