# Generated by Django 2.1.3 on 2018-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181204_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
