services:
  chrome:
    depends_on: [selenium-hub]
    environment: [HUB_HOST=selenium-hub, HUB_PORT=4444]
    image: selenium/node-chrome:3
    volumes: ['/dev/shm:/dev/shm']
  db:
    environment: {POSTGRES_DB: db, POSTGRES_HOST_AUTH_METHOD: trust}
    healthcheck:
      interval: 5s
      retries: 7
      start_period: 3s
      test: [CMD-SHELL, pg_isready -U postgres]
      timeout: 5s
    image: postgres:9.6
    ports: ['5432:5432']
    volumes: ['.:/app:rw']
  firefox:
    depends_on: [selenium-hub]
    environment: [HUB_HOST=selenium-hub, HUB_PORT=4444]
    image: selenium/node-firefox:3
    volumes: ['/dev/shm:/dev/shm']
  mail:
    image: dockage/mailcatcher:0.6.5
    ports: ['1025:1025', '1080:1080']
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:3
    ports: ['4444:4444']
  web:
    depends_on:
      db: {condition: service_healthy}
      mail: {condition: service_started}
    extends: web-base
    links: ['db:postgres']
    volumes: ['.:/app:rw']
  web-base:
    build: .
    command: gunicorn --reload --bind=0.0.0.0:8000 eahub.config.wsgi
    env_file: [.env]
    ports: ['8000:8000']
    volumes: ['./data:/data:rw']
  web-e2e:
    depends_on:
      chrome: {condition: service_started}
      db: {condition: service_healthy}
      mail: {condition: service_started}
    extends: web-base
    links: ['db:postgres']
version: '2'
