# Generated by Django 2.1.7 on 2019-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisational_affiliation',
            field=models.TextField(blank=True),
        ),
    ]
