# Generated by Django 2.1.7 on 2019-03-04 20:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import eahub.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0002_import_from_airtable'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localgroups.LocalGroup')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='organisational_affiliations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(default=1, enum=eahub.profiles.models.OrganisationalAffiliation), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='local_groups',
            field=models.ManyToManyField(blank=True, through='profiles.Membership', to='localgroups.LocalGroup'),
        ),
    ]
