# Generated by Django 2.1.7 on 2019-02-28 20:05

import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields
import eahub.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisational_affiliations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(default=1, enum=eahub.profiles.models.OrganisationalAffiliation), blank=True, default=list, size=None),
        ),
    ]
