# Generated by Django 2.1.7 on 2019-03-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0002_import_from_airtable'),
        ('profiles', '0002_profile_organisational_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='localgroups.LocalGroup'),
        ),
    ]
