# Generated by Django 2.2b1 on 2019-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cause_areas_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
