# Generated by Django 2.1.7 on 2019-03-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, to='localgroups.LocalGroup'),
        ),
    ]
