# Generated by Django 2.2b1 on 2019-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cause_areas_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise_areas_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='topics_i_speak_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
