# Generated by Django 2.2.4 on 2019-08-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0011_profile_career_interest_areas")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_website_url",
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
