# Generated by Django 2.2.16 on 2020-12-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profiles", "0015_profile_email_visible")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="email_visible", new_name="allow_messaging"
        )
    ]
