# Generated by Django 2.2.16 on 2021-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_profile_offering_looking_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allow_messaging",
            field=models.BooleanField(default=True),
        ),
    ]
