# Generated by Django 2.2.16 on 2021-02-19 13:37

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import eahub.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_profile_offering_looking_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTagType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    enumfields.fields.EnumField(
                        enum=eahub.profiles.models.ProfileTagTypeEnum, max_length=128
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.Profile",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(blank=True, to="profiles.ProfileTagType"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="tags_cause_area",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eahub.profiles.models.ProfileTagTypeEnum(
                        "cause_area"
                    )
                },
                related_name="tags_cause_area",
                to="profiles.ProfileTag",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags_expertise_area",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eahub.profiles.models.ProfileTagTypeEnum(
                        "expertise_area"
                    )
                },
                related_name="tags_expertise_area",
                to="profiles.ProfileTag",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags_generic",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eahub.profiles.models.ProfileTagTypeEnum("generic")
                },
                related_name="tags_generic",
                to="profiles.ProfileTag",
            ),
        ),
    ]
