# Generated by Django 2.2.16 on 2021-02-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_add_profile_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="causes",
        ),
        migrations.AddField(
            model_name="profile",
            name="cause_areas_new",
            field=models.ManyToManyField(
                blank=True, related_name="cause_areas", to="profiles.ProfileTag"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="expertise_areas_new",
            field=models.ManyToManyField(
                blank=True, related_name="expertise_areas", to="profiles.ProfileTag"
            ),
        ),
    ]
