# Generated by Django 2.2.16 on 2021-02-19 16:53

from django.db import migrations, models
import eahub.profiles.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_add_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletag',
            old_name='is_verified',
            new_name='is_featured',
        ),
        migrations.AddField(
            model_name='profiletag',
            name='status',
            field=enumfields.fields.EnumField(default='approved', enum=eahub.profiles.models.ProfileTagStatus, max_length=64),
        ),
        migrations.AlterField(
            model_name='profiletag',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='profiletag',
            name='types',
            field=models.ManyToManyField(to='profiles.ProfileTagType'),
        ),
    ]
