# Generated by Django 2.2.16 on 2021-02-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_add_fields_tag_status_and_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiletag",
            name="also_known_as",
            field=models.TextField(blank=True),
        ),
    ]
