# Generated by Django 2.2.16 on 2021-02-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_add_field_tag_also_known_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletag',
            name='also_known_as',
        ),
        migrations.AddField(
            model_name='profiletag',
            name='synonyms',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
