# Generated by Django 2.2.16 on 2021-02-19 22:25

from django.db import migrations, models

import eahub.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_rename_field_also_known_as_to_synonyms"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tags_career_interest",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eahub.profiles.models.ProfileTagTypeEnum(
                        "career_interest"
                    )
                },
                related_name="tags_career_interest",
                to="profiles.ProfileTag",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags_organisational_affiliation",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eahub.profiles.models.ProfileTagTypeEnum(
                        "organisational_affiliation"
                    )
                },
                related_name="tags_organisational_affiliation",
                to="profiles.ProfileTag",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags_pledge",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eahub.profiles.models.ProfileTagTypeEnum("pledge")
                },
                related_name="tags_pledge",
                to="profiles.ProfileTag",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags_speech_topic",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eahub.profiles.models.ProfileTagTypeEnum(
                        "speech_topic"
                    )
                },
                related_name="tags_speech_topic",
                to="profiles.ProfileTag",
            ),
        ),
    ]
