# Generated by Django 2.2.17 on 2021-08-08 10:06

from django.db import migrations, models
import eahub.profiles.models
import enumfields.fields


def migrate_profiles_to_privacy_agreement(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    for profile in Profile.objects.all():
        profile.privacy_policy_agreed = True
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0027_add_fields_twitter_and_calendly"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="privacy_policy_agreed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=migrate_profiles_to_privacy_agreement,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
