# Generated by Django 2.2.26 on 2022-02-11 22:23

from django.db import migrations
import eahub.profiles.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_add_privacy_policy_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visibility',
            field=enumfields.fields.EnumField(default='public', enum=eahub.profiles.models.VisibilityEnum, max_length=16, verbose_name='Profile visibility'),
        ),
    ]
