# Generated by Django 3.2.15 on 2024-03-31 14:57

import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields
import eahub.profiles.legacy
import eahub.profiles.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_add_privacy_policy_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career_interest_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=eahub.profiles.legacy.ExpertiseArea), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cause_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=eahub.profiles.legacy.CauseArea), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=eahub.profiles.legacy.ExpertiseArea), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='giving_pledges',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=eahub.profiles.legacy.GivingPledge), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organisational_affiliations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=eahub.profiles.legacy.OrganisationalAffiliation), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility',
            field=enumfields.fields.EnumField(default='public', enum=eahub.profiles.models.VisibilityEnum, max_length=16, verbose_name='Profile visibility'),
        ),
    ]
