# Generated by Django 2.2.26 on 2022-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20220211_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opt_in_to_matchmaking',
            field=models.BooleanField(blank=True, default=True, help_text='Your email address WILL be visible to them', verbose_name='Allow approved users to be matched with me'),
        ),
    ]
