# Generated by Django 2.2b1 on 2019-03-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localgroup',
            options={'ordering': ['name', 'slug']},
        ),
    ]
