# Generated by Django 2.1.7 on 2019-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0002_import_from_airtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
