# Generated by Django 2.2b1 on 2019-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0003_organisership'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
