# Generated by Django 2.2.2 on 2019-06-19 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("localgroups", "0003_localgroup_last_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localgroup",
            name="organisers",
            field=models.ManyToManyField(
                blank=True,
                related_name="organiser_localgroup_set",
                through="localgroups.Organisership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PastOrganisership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="localgroups.LocalGroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="localgroup",
            name="past_organisers",
            field=models.ManyToManyField(
                blank=True,
                related_name="past_organiser_localgroup_set",
                through="localgroups.PastOrganisership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
