# Generated by Django 2.2.10 on 2020-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0004_localgroup_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroup',
            name='other_website',
            field=models.URLField(blank=True),
        ),
    ]
