# Generated by Django 2.2.10 on 2020-04-05 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("localgroups", "0004_localgroup_is_public")]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="other_info",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]
            ),
        )
    ]
