# Generated by Django 2.2.10 on 2020-04-11 14:34

from django.apps import apps
import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields
import eahub.localgroups.models

class Migration(migrations.Migration):

    dependencies = [
        ("localgroups", "0004_localgroup_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="local_group_types",
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(default=1, enum=eahub.localgroups.models.LocalGroupType), blank=True, default=list, size=None),
        )
    ]
