# Generated by Django 2.2.10 on 2020-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("localgroups", "0005_localgroup_other_info")]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="other_website",
            field=models.URLField(blank=True),
        )
    ]
