# Generated by Django 2.2.10 on 2020-03-29 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0005_localgroup_other_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroup',
            name='other_info',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
