# Generated by Django 2.2.10 on 2020-04-11 14:34

from django.apps import apps
import django.contrib.postgres.fields
from django.db import migrations
from django.db.models import F
import django_enumfield.db.fields
import eahub.localgroups.models

class Migration(migrations.Migration):

    dependencies = [
        ("localgroups", "0005_localgroup_local_group_types"),
    ]

    operations = [
        migrations.RemoveField("LocalGroup", "local_group_types")
    ]
