# Generated by Django 2.2.10 on 2020-03-29 15:41

import django.contrib.postgres.fields
import django_enumfield.db.fields
from django.db import migrations

import eahub.localgroups.models


class Migration(migrations.Migration):

    dependencies = [("localgroups", "0004_localgroup_is_public")]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="local_group_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django_enumfield.db.fields.EnumField(
                    default=1, enum=eahub.localgroups.models.LocalGroupType
                ),
                blank=True,
                default=list,
                size=None,
            ),
        )
    ]
