# Generated by Django 2.2.10 on 2020-04-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0006_localgroup_other_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localgroup',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='localgroup',
            name='other_website',
        ),
    ]
