# Generated by Django 2.2.10 on 2020-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0007_localgroup_local_group_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroup',
            name='organisers_freetext',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
