# Generated by Django 2.2.10 on 2020-08-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0007_localgroup_local_group_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroup',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localgroup',
            name='name',
            field=models.CharField(help_text='University groups: Ideally avoid acronyms in your group name unless they are likely to be unique worldwide. If the name of your university is also the name of a city, indicate in the name that this is a university group.', max_length=100, verbose_name='name of group'),
        ),
    ]
