# Generated by Django 2.2.10 on 2020-09-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0008_localgroup_organisers_freetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroup',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localgroup',
            name='organisers_freetext',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organisers (Non EA Hub members)'),
        ),
    ]
