# Generated by Django 3.2.15 on 2024-03-31 14:57

import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields
import eahub.localgroups.models


class Migration(migrations.Migration):

    dependencies = [
        ('localgroups', '0009_localgroup_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgroup',
            name='local_group_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=eahub.localgroups.models.LocalGroupType), blank=True, default=list, size=None),
        ),
    ]
