# Generated by Django 2.1.3 on 2018-11-14 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='city_or_town',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='facebook_group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='facebook_page',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
