# Generated by Django 2.1.4 on 2018-12-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eahub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='organiser',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
