# Generated by Django 2.1.3 on 2018-11-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eahub', '0002_auto_20181114_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lean_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='official_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='organiser_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
