# Generated by Django 2.1.3 on 2018-12-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eahub', '0003_auto_20181114_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
