# Generated by Django 2.1.4 on 2018-12-18 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_organiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='organiser',
        ),
        migrations.AddField(
            model_name='group',
            name='donations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='images',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='links',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='meetup_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='meetup_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='organisers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='serves_as',
            field=models.TextField(null=True),
        ),
    ]
