# Generated by Django 2.1.4 on 2018-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20181218_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
