# Generated by Django 2.1.4 on 2018-12-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='serves_as',
        ),
    ]
