# Generated by Django 2.1.4 on 2019-01-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20190105_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='edit_history',
            field=models.TextField(default='{}'),
        ),
    ]
