# Generated by Django 2.1.5 on 2019-01-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20190119_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='lean_email',
        ),
    ]
