# Generated by Django 2.1.5 on 2019-01-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_group_lean_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('COUNTRY', 'Country'), ('CITY', 'City'), ('UNIVERSITY', 'University')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='meetups_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='total_group_donations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
