# Generated by Django 2.1.5 on 2019-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20190129_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('COUNTRY', 'Country'), ('CITY', 'City'), ('UNIVERSITY', 'University'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
    ]
