# Generated by Django 2.1.5 on 2019-02-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20190206_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='total_group_donations',
        ),
    ]
