# Generated by Django 2.1.5 on 2019-02-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_remove_group_total_group_donations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='official_email',
            new_name='email',
        ),
    ]
