# Generated by Django 2.1.7 on 2019-02-17 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20190206_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='airtable_record',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
