on: [pull_request]


jobs:
    run_pytest:
        name: run code styles checks & tests
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: run pytest
              shell: bash
              run: docker-compose run --use-aliases web pytest
