on: [pull_request]


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: test
              shell: bash
              run: docker-compose run --use-aliases web pytest
