on: [pull_request]


jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the current brnach of eahub.org repository
              uses: actions/checkout@v2
            - name: run pytest
              shell: bash
              run: docker-compose run --use-aliases web pytest
