# Generated by Django 2.2.16 on 2021-01-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=30)),
                ("message", models.CharField(max_length=2000)),
                ("page_url", models.CharField(blank=True, max_length=50)),
            ],
        )
    ]
