# Generated by Django 2.2.16 on 2021-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="creation_time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="page_url",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
