# Generated by Django 2.2.17 on 2021-04-06 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2021, 4, 6, 13, 34, 19, 796325, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="Email (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(verbose_name="Feedback"),
        ),
    ]
