on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch:
        inputs:
            name:
                description: 'Trigger a pytest run'
jobs:
    pytest:
        name: run code styles checks & tests
        runs-on: ubuntu-latest
        steps:
            - name: checkout the current brnach of eahub.org repository
              uses: actions/checkout@v2
            - name: run pytest
              shell: bash
              run: docker-compose run --use-aliases web pytest
